# Generated by Django 4.2 on 2026-06-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
