# Generated by Django 4.2 on 2026-06-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
