# Generated by Django 4.2 on 2026-06-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_location_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='film',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
