# Generated by Django 4.2 on 2026-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_photo_camera_photo_film_photo_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
