# Generated by Django 4.2 on 2026-06-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_photo_aperture_photo_focal_length_photo_iso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
