# Generated by Django 4.2 on 2026-06-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_aboutimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='places.area'),
        ),
    ]
