# Generated by Django 4.2 on 2026-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gear_type', models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('film', 'Film'), ('accessory', 'Accessory')], default='camera', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gear/')),
            ],
        ),
    ]
