# Generated by Django 4.2 on 2026-06-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='locations/large/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='locations/medium/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='locations/thumb/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='locations/large/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='locations/medium/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='locations/thumb/'),
        ),
    ]
