# Generated by Django 4.2 on 2026-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_location_image_large_location_image_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='areas/large/'),
        ),
        migrations.AddField(
            model_name='area',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='areas/medium/'),
        ),
        migrations.AddField(
            model_name='area',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='areas/thumb/'),
        ),
    ]
