# Generated by Django 4.2 on 2026-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ja', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locations', to='places.tag'),
        ),
    ]
