# Generated by Django 4.2 on 2026-07-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_tag_location_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id']},
        ),
    ]
