# Generated by Django 4.2 on 2026-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_photo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='about/large/'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='about/medium/'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='about/thumb/'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='about/large/'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='about/medium/'),
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='about/thumb/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='collaborators/large/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='collaborators/medium/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='collaborators/thumb/'),
        ),
        migrations.AddField(
            model_name='gear',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='gear/large/'),
        ),
        migrations.AddField(
            model_name='gear',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='gear/medium/'),
        ),
        migrations.AddField(
            model_name='gear',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='gear/thumb/'),
        ),
    ]
