# Generated by Django 4.2 on 2026-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_about_image_large_about_image_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
