# Generated by Django 4.2 on 2026-07-20 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_location_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
