# Generated by Django 4.2 on 2026-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_alter_location_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_ja',
            field=models.TextField(blank=True, verbose_name='Description (Japanese)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(verbose_name='Description (English)'),
        ),
    ]
