# Generated by Django 4.2 on 2026-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_location_description_ja_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='collection',
            field=models.CharField(choices=[('hiroshima', 'Hiroshima'), ('japan', 'Japan')], db_index=True, default='hiroshima', max_length=20),
        ),
    ]
