# Generated by Django 4.2 on 2026-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_area_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.CharField(default='Japan', max_length=100),
        ),
    ]
