# Generated by Django 4.2 on 2026-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_area_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='visited_at',
            field=models.DateField(blank=True, null=True, verbose_name='Visited'),
        ),
        migrations.AlterField(
            model_name='area',
            name='country',
            field=models.CharField(db_index=True, default='Japan', max_length=100),
        ),
    ]
