# Generated by Django 4.2 on 2026-07-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_area_visited_at_alter_area_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='visited_at',
        ),
    ]
