# Generated by Django 4.2 on 2026-07-30 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0027_remove_area_visited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='carp/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
