# Generated by Django 4.2 on 2026-07-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_carpnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='carp/header/')),
                ('title', models.CharField(default='Carp Today', max_length=100)),
                ('subtitle', models.TextField(default='Latest Hiroshima Carp news for visitors and baseball fans.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
