# Generated by Django 4.2 on 2026-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_carppagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpnews',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='carp/webp/'),
        ),
        migrations.AddField(
            model_name='carppagesettings',
            name='hero_image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='carp/header/webp/'),
        ),
    ]
