# Generated by Django 4.2 on 2026-08-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_photo_processing_error_photo_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exhibition_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
