# Generated by Django 4.2 on 2026-08-14 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0032_photo_exhibition_order_photo_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='journal/large/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='journal/medium/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='journal/thumb/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal/')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='journal/large/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='journal/medium/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='journal/thumb/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.journalarticle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
