# Generated by Django 4.2 on 2026-08-14 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0033_journalarticle_journalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary/')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='diary/large/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='diary/medium/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='diary/thumb/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
