# Generated by Django 4.2 on 2026-08-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_diarypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary/photos/')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='diary/photos/large/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='diary/photos/medium/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='diary/photos/thumb/')),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.diarypost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
