# Generated by Django 4.2 on 2026-09-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0035_diaryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ダム湖名')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('dam_name', models.CharField(max_length=200, verbose_name='ダム名')),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('visited', models.BooleanField(db_index=True, default=False, verbose_name='訪問済み')),
                ('photographed', models.BooleanField(db_index=True, default=False, verbose_name='撮影済み')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='訪問日')),
                ('excerpt', models.TextField(blank=True, verbose_name='概要')),
                ('description', models.TextField(blank=True, verbose_name='紹介文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dam_lakes/', verbose_name='メイン画像')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='dam_lakes/large/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='dam_lakes/medium/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='dam_lakes/thumb/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ダム湖百選',
                'verbose_name_plural': 'ダム湖百選',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='dam_lake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_articles', to='places.damlake', verbose_name='ダム湖百選'),
        ),
    ]
