# Generated by Django 4.2 on 2026-09-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0036_damlake_journalarticle_dam_lake'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamLakePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dam_lakes/photos/', verbose_name='写真')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='キャプション')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.damlake', verbose_name='ダム湖')),
            ],
            options={
                'verbose_name': 'ダム湖写真',
                'verbose_name_plural': 'ダム湖写真',
                'ordering': ['order', 'id'],
            },
        ),
    ]
