# Generated by Django 4.2 on 2026-09-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0037_damlakephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='damlakephoto',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='dam_lakes/photos/large/', verbose_name='Large'),
        ),
        migrations.AddField(
            model_name='damlakephoto',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='dam_lakes/photos/medium/', verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='damlakephoto',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='dam_lakes/photos/thumb/', verbose_name='Thumb'),
        ),
    ]
