# Generated by Django 4.2 on 2026-09-06 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0038_damlakephoto_image_large_damlakephoto_image_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaguraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公演名')),
                ('date', models.DateField(verbose_name='公演日')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='会場')),
                ('venue_address', models.CharField(blank=True, max_length=300, verbose_name='会場住所')),
                ('description', models.TextField(blank=True, verbose_name='公演について')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '神楽公演',
                'verbose_name_plural': '神楽公演',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KaguraJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('excerpt', models.TextField(blank=True, verbose_name='概要')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kagura/journal/', verbose_name='メイン画像')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='kagura/journal/medium/', verbose_name='Medium')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='places.kaguraevent', verbose_name='神楽公演')),
            ],
            options={
                'verbose_name': '神楽Journal',
                'verbose_name_plural': '神楽Journal',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KaguraPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='演目名')),
                ('name_en', models.CharField(max_length=150, verbose_name='英語名')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='簡単な説明')),
                ('story', models.TextField(blank=True, verbose_name='ストーリー')),
                ('characters', models.TextField(blank=True, verbose_name='登場人物')),
                ('highlights', models.TextField(blank=True, verbose_name='見どころ')),
                ('costume_description', models.TextField(blank=True, verbose_name='衣装・仮面')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kagura/', verbose_name='メイン画像')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='kagura/medium/', verbose_name='Medium')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '神楽演目',
                'verbose_name_plural': '神楽演目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KaguraTroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='神楽団名')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英語名')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='紹介')),
                ('style', models.CharField(blank=True, max_length=200, verbose_name='スタイル')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Webサイト')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '神楽団',
                'verbose_name_plural': '神楽団',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='diaryphoto',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='diaryphoto',
            name='image_thumb',
        ),
        migrations.CreateModel(
            name='KaguraPerformancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kagura/photos/', verbose_name='写真')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='kagura/photos/medium/', verbose_name='Medium')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='キャプション')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.kaguraperformance', verbose_name='演目')),
            ],
            options={
                'verbose_name': '神楽演目写真',
                'verbose_name_plural': '神楽演目写真',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KaguraJournalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kagura/journal/photos/', verbose_name='写真')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='kagura/journal/photos/medium/', verbose_name='Medium')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='キャプション')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.kagurajournal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': '神楽Journal写真',
                'verbose_name_plural': '神楽Journal写真',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='kaguraevent',
            name='performances',
            field=models.ManyToManyField(blank=True, related_name='events', to='places.kaguraperformance', verbose_name='演目'),
        ),
        migrations.AddField(
            model_name='kaguraevent',
            name='troupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='places.kaguratroupe', verbose_name='神楽団'),
        ),
    ]
