# Generated by Django 4.2 on 2026-09-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0039_kaguraevent_kagurajournal_kaguraperformance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypost',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='diarypost',
            name='image_thumb',
        ),
    ]
