# Generated by Django 4.2 on 2026-09-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0040_remove_diarypost_image_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damlake',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='damlake',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='damlakephoto',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='damlakephoto',
            name='image_thumb',
        ),
        migrations.AlterField(
            model_name='damlake',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='dam_lakes/medium/', verbose_name='Medium'),
        ),
    ]
